env: safetyGraphics
label: Adverse Event Timelines
type: htmlwidget
package: safetyCharts
export: false 
domain: 
  - aes
workflow:
  widget: aeTimelines
links:
  Homepage: https://github.com/RhoInc/ae-timelines
  Wiki: https://github.com/RhoInc/ae-timelines/wiki 
  Issues: https://github.com/RhoInc/ae-timelines/issues
  Demo: https://rhoinc.github.io/ae-timelines/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts

