label: Paneled Outlier Explorer (widget)
type: htmlwidget
domain: labs
package: safetyCharts
export: true
workflow:
  init: init_paneledOutlierExplorer
  widget: paneledOutlierExplorer
links:
  Homepage: https://github.com/RhoInc/paneled-outlier-explorer
  Wiki: https://github.com/RhoInc/paneled-outlier-explorer/wiki 
  Issues: https://github.com/RhoInc/paneled-outlier-explorer/issues
  Demo: https://rhoinc.github.io/paneled-outlier-explorer/test-page/
  htmlwidget: https://github.com/SafetyGraphics/safetycharts

