env: safetyGraphics
label: Delta-Delta
type: htmlwidget
package: safetyCharts
export: true
domain: 
  - labs
dataSpec:
  labs:
    - id_col
    - visit_col
    - visitn_col
    - measure_col
    - value_col
workflow:
  widget: safetyDeltaDelta
links:
  Homepage: https://github.com/RhoInc/safety-delta-delta
  Wiki: https://github.com/RhoInc/safety-delta-delta/wiki 
  Issues: https://github.com/RhoInc/safety-delta-delta/issues
  Demo: https://rhoinc.github.io/safety-delta-delta/test-page/
  safetyCharts: https://github.com/SafetyGraphics/safetycharts

